import { Noto_Sans } from "next/font/google";
import "./helpers/reset.css";
import "./global.css";
import { Metadata } from "next";
import React, { FunctionComponent } from "react";
import { Header } from "./layout/Header/Header";
import { Sidebar } from "./layout/Sidebar/Sidebar";
import { Footer } from "./layout/Footer/Footer";
import styles from "./Layout.module.css";

const notoSans = Noto_Sans({
	weight: "400",
	style: "normal",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "MyTop - лучший сайт отзывов",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={notoSans.className}>
				<div className={styles.wrapper}>
					<Header className={styles.header}></Header>
					<Sidebar className={styles.sidebar}></Sidebar>
					<div className={styles.body}>
						<div>{children}</div>
					</div>
					<Footer className={styles.footer}></Footer>
				</div>
			</body>
		</html>
	);
}
