import {Noto_Sans} from "next/font/google";
import "./helpers/reset.css";
import "./global.css";

const notoSans = Noto_Sans({
  weight: "400",
  style: "normal",
  subsets:["latin"],
});


export const metadata = {
  title: "MyTop - лучший сайт отзывов",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
